version: '3'

services:
  nginx-gateway:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        ENV_NAME: dev
    container_name: nginx-gateway
    image: nginx-gateway
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - 'www.example.com:127.0.0.1'
      - 'ssl.example.com:127.0.0.1'
    environment:
      ENV_NAME: dev
